export const blogData = [
    {
      id: 1,
      date: "Dec 20th, 2022",
      name: 'Blog 1',
      likes: '12.5k',
      comment: '9k',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg:'/Images/blog1.png',
    },
    {
      id: 2,
      date: "Oct 15th, 2022",
      name: 'Blog 2',
      likes: '3.4k',
      comment: '1.5k',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg: '/Images/blog2.png',
    },
    {
      id: 3,
      date: "sept 25th, 2022",
      name: 'Blog 3',
      likes: '9.4k',
      comment: '7.3k',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg: '/Images/blog3.png',
    },

    {
      id: 4,
      date: "July 8th, 2022",
      name: 'Blog 4',
      likes: '13.2k',
      comment: '9k',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg: '/Images/blog2.png',
    },
    {
      id: 5,
      date: "March 20th, 2022",
      name: 'Blog 5',
      likes: '7.9k',
      comment: '6.4',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg: '/Images/blog3.png',
    },
    {
      id: 6,
      date: "Jan 18th, 2022",
      name: 'Blog 6',
      likes: '10.7k',
      comment: '8.5k',
      info: 'Townhall different from babablu...blu blu.. bulabla.....',
      linkImg: '/Images/blog1.png',
    }
  ];