export const collectionData = [
    {
      id: 1,
      kind: "Music",
      name: 'NFT 1',
      eth: '1.5ETH',
      price: '$24.7',
      percent: '-23.5%',
      info: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.',
      linkImg:'/Images/image 6.png',
    },
    {
      id: 2,
      kind: "Metaverse",
      name: 'NFT 2',
      eth: '3.2ETH',
      price: '$24.7',
      percent: '+12.7%',
      info: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.',
      linkImg: '/Images/image 7.png',
    },
    {
      id: 3,
      kind: "Sports",
      name: 'NFT 3',
      eth: '0.85ETH',
      price: '$24.7',
      percent: '+18.5%',
      info: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.',
      linkImg: '/Images/image 8.png',
    },

    {
      id: 4,
      kind: "Music",
      name: 'NFT 4',
      eth: '1.31ETH',
      price: '$24.7',
      percent: '-23.5%',
      linkImg: '/Images/image 9.png',
    },
    {
      id: 5,
      kind: "Metaverse",
      name: 'NFT 5',
      eth: '0.045ETH',
      price: '$24.7',
      percent: '-3.5%',
      linkImg: '/Images/image 11.png',
    },
    {
      id: 6,
      kind: "Music",
      name: 'NFT 6',
      eth: '1.156ETH',
      price: '$24.7',
      percent: '+23.5%',
      linkImg: '/Images/image 12.png',
    },
    {
      id: 7,
      kind: "Sports",
      name: 'NFT 7',
      eth: '2.53ETH',
      price: '$24.7',
      percent: '+34.9%',
      linkImg: '/Images/image 14.png',
    },

    {
      id: 8,
      kind: "Metaverse",
      name: 'NFT 8',
      eth: '1.27ETH',
      price: '$24.7',
      percent: '-32.5%',
      linkImg: '/Images/image 15.png',
    },
    {
      id: 9,
      kind: "Sports",
      name: 'NFT 9',
      eth: '2.46ETH',
      price: '$24.7',
      percent: '+3.35%',
      linkImg: '/Images/Rectangle 12.png',
    },
    {
      id: 10,
      kind: "Sports",
      name: 'NFT 10',
      eth: '2.53ETH',
      price: '$32.2',
      percent: '+14.9%',
      linkImg: '/Images/Rectangle 13.png',
    },
    {
      id: 11,
      kind: "Music",
      name: 'NFT 11',
      eth: '1.27ETH',
      price: '$16.7',
      percent: '-32.5%',
      linkImg: '/Images/Rectangle 14.png',
    },
    {
      id: 12,
      kind: "Metaverse",
      name: 'NFT 12',
      eth: '1.27ETH',
      price: '$24.7',
      percent: '+29.5%',
      linkImg: '/Images/Group 126.png',
    }
  ];